### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.symbol.emdk.EMDKManager$EMDKListener" on path: DexPathList

### ISSUE THREAD

**Issue by gilbertgit** [Zebra/zebra.github.io#3]
Hi,
I'm using a TC77 that is running EMDK version 7.2.2.2202.
I get this error when trying to instantiate My EMDKWrapper class that implements EMDKListener. This does not happen every time time I run the app.
I'm using the latest EMDK from the plugin manager in Android Studio.

Manifest:
`<uses-permission android:name="com.symbol.emdk.permission.EMDK"/>`
`<uses-library android:name="com.symbol.emdk" android:required="false"/>`

App Gradle:
`compileOnly 'com.symbol:emdk:7.4.24'`

What am I missing?

Thank you!

**Comment by Farahat** [comment]
any updates?

**Comment by nitinguna** [comment]
make <uses-library android:name="com.symbol.emdk" android:required="false"/> part of application 
try with compileOnly 'com.symbol:emdk:7.6.10'

**Comment by rxbynerd** [comment]
I've fixed this by bumping `compileOnly` up to `implementation` in my `app/build.gradle`, but I'm pretty convinced that's not the "right way" to solve this

**Comment by rxbynerd** [comment]
Found out this was caused in my setup due to a missing `<uses-library android:name="com.symbol.emdk"/>` in my `AndroidManifest.xml` (under `<manifest>`, from [BarcodeSample1](https://github.com/ZebraDevs/EMDK-Android-Samples/blob/9450174c98b5612da8e56eb73867262e885582af/BarcodeSample1/app/src/main/AndroidManifest.xml#L5))

Based on the contents of the original issue, I would say drop the `android:required="false"`

**Comment by MikeDimmickMnetics** [comment]
The `com.symbol.emdk.jar` supplied in the EMDK (through the installer for versions before is not usable at runtime. It's merely a collection of stubs that provide the right interface, with the right signature. All the methods will throw a `RuntimeException` (you can see this in Android Studio if you go to the Project view, External Libraries, and drill down through Gradle: com.symbol:emdk:7.4.24). To get things to work, you have to ask Android to load the real version preinstalled on the device, instead of this stub version. That's what the `<uses-library>` element in `AndroidManifest.xml` does.

I suspect that the original problem was that this element was put in the wrong place, or actually omitted. It has to be a child of the `<application>` element, while `<uses-permission>` is a child of the `<manifest>` element. Although, I've just found that putting `<uses-library>` directly under `<manifest>` causes AAPT to fail with an error (using the Oreo 8.0 SDK, API level 26).

Setting `android:required="false"` means that your APK can be installed on devices that don't have the EMDK available (such as an emulator). If you don't set this, `adb install` will report `Error: INSTALL_FAILED_MISSING_SHARED_LIBRARY` for non-Zebra devices. If you only want to offer your app for Zebra devices, that won't necessarily be a problem, but will stop you using an emulator.

Using `implementation` will cause Gradle to include the stub version in your APK (in `classes.dex`). That doesn't cause a problem as such on a Zebra device - the built-in shared library takes precedence, so you'll never see the `RuntimeException` - but it wastes space. If you use `compileOnly`, Gradle only uses the interface definition from `com.symbol.emdk.jar`, it does not include the classes in the final `classes.dex`. You can see the difference if you use something like [Apktool](https://ibotpeaches.github.io/Apktool/) to inspect your APK.

If you have used `implementation` and `android:required="false"`, then using any EMDK feature on a non-Zebra device will throw a `RuntimeException`, as it'll use the stub implementation. If you use `compileOnly` then you'll need to use reflection to determine if the EMDK is available ([example](https://stackoverflow.com/questions/43307012/how-to-catch-noclassdeffounderror-exception-to-use-an-optional-case)). Your main activity can't implement the `EMDKManager.EMDKListener` interface, because Android will only be able to instantiate it if some definition is available, so you'll need to move that to a different class.

**Comment by MikeDimmickMnetics** [comment]
In short:

If you only want to run on Zebra devices, use `compileOnly` and `<uses-library android:name="com.symbol.emdk" android:required="true">` to save a little space.

If you want to also run on non-Zebra devices, use `implementation` and `<uses-library android:name="com.symbol.emdk" android:required="false">`, then catch `java.lang.RuntimeException` or use reflection to determine if the EMDK is available.

If you want to also run on non-Zebra devices but don't want the stub EMDK to be included in your package, use `compileOnly` and `<uses-library android:name="com.symbol.emdk" android:required="false">`, but you'll need to implement your code in such a way that it never constructs anything that references the EMDK unless the EMDK is present.

`compileOnly` looks like it saves about 150 kB, so it probably isn't worth it.

**Comment by MikeDimmickMnetics** [comment]
I've just got caught out by this again! If you have to still support older devices, you need to use `compileOnly`. On Android KitKat (4.4), you get a "Class resolved by unexpected DEX" error if you use `implementation`.

I think the reason it works on newer devices is probably that Android uses the ART virtual machine in place of Dalvik, from Android 5.0 (Lollipop) onwards.

**Comment by acaliaro** [comment]
I have an application that uses the EMDK but which also works on devices from other vendors. The EMDK is used in a particular class which is instantiated only if the device is a Zebra. On some honeywells I still get the error "Didn't find class" com.symbol.emdk.EMDKManager $ EMDKListener "" but I don't understand why, since I don't do the "new MyZebraClass" for honeywells.

In the manifest I have

         <uses-library
             android: name = "com.symbol.emdk"
             android: required = "false" />

While in the gradle

     compileOnly 'com.symbol: emdk: 9.1.1'

**Comment by williamheelis** [comment]
I'm having a problem with this, I am trying to get emdk to build as a `react native typescript` external `java` module, which if i'm honest, should work. But everytime I build I get this:

```
info JS server already running.
info Building the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.symbol:emdk:9.1+ as no versions of com.symbol:emdk are available.
     Searched in the following locations:
       - file:/Users/c0b0dpd/Documents/sg_future/ps20-release/PS20Release/node_modules/react-native/android/com/symbol/emdk/maven-metadata.xml
       - file:/Users/c0b0dpd/Documents/sg_future/ps20-release/PS20Release/node_modules/jsc-android/dist/com/symbol/emdk/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/symbol/emdk/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/symbol/emdk/maven-metadata.xml
       - https://www.jitpack.io/com/symbol/emdk/maven-metadata.xml
     Required by:
         project :app
```

also, I am concerned that I can't see any information on where these `com.symbol:emdk` libraries are defined - EG: where is the list that says `9.1.1` or `11.0.1` or whatever? why don't zebra show that sort of information?

**Comment by williamheelis** [comment]
this is the error if I run it in android studio direct
<img width="1774" alt="Screenshot 2022-03-14 at 16 03 17" src="https://user-images.githubusercontent.com/82875267/158212405-7d0ab910-db5b-4d6b-b9f5-df65fb768d7c.png">

**Comment by MikeDimmickMnetics** [comment]
@williamheelis The [Zebra TechDocs site](https://techdocs.zebra.com/) lists the available developer tools. Under 'EMDK for Android' there is a drop-list in the upper right corner, which lists all the version numbers. Clicking a version takes you to the documentation for that version. From there, click 'Set Up' in the top bar to get to the set-up instructions.

Versions 9.1.1 and before were on the JCenter Maven repository. This is now read-only. It was going to be deleted entirely, but since it was a core part of most Java developers' builds, thankfully the owner was persuaded to keep it up indefinitely. You can search JCenter at https://mvnrepository.com/artifact/com.symbol/emdk.

9.1.1 and later seem to be on a Zebra cloud instance of Artifactory. [The instructions are in the version 11 documentation.](https://techdocs.zebra.com/emdk-for-android/11-0/guide/setup/#enableemdksdk) This seems to just be a re-release of 9.1's documentation with a new version number: if you actually look at the repository (by following the link in the documentation), the version number is 9.1.1.

To fix your issue, you need to either put `jcenter()`, or the new URL in the v11 instructions, in the `repositories` section of the gradle file.

I'm also not sure that your dependency specification is correct. Looking at the [Gradle documentation](https://docs.gradle.org/current/userguide/dependency_management.html#single-version-declarations), this pattern is called a 'prefix version range'. All the examples have a dot immediately before the +, e.g. 'com.symbol:emdk:9.1.+'. You have '9.1+'. I'm not sure if a hypothetical version 9.10 would match this or not. [Google recommend not using dynamic versions](https://developer.android.com/studio/build/dependencies).

**Comment by williamheelis** [comment]
> 

thanks (forgive me) but I have to say: your advice isn't correct. for every single api version the set up says the exact same thing :

`compileOnly 'com.symbol:emdk:x.x.x' //  e.g. ‘com.symbol:emdk:7.6.10’` 

yet crucially for every single build version, the minor increment number is ALWAYS missing:

EG: if I want to access `11.0.x` I am in the dark, and need to guess whether it is `11.0`.`1`,`2`/`3`/`4`/`5`/`6`/`7`/`8`/`9`/`10` and when they all say 'failed to resolve' it is impossible to diagnose

secondly the instructions for `9.1.?` are different to the instructions for `9.0.?` they seem unable to differnetiate bewten the `app` `build.gradle` and the `project` `build.gradle` and never seem to differentiate between the two what is supposed to go where. Lastly they documentation doesn't declare the minimum `"com.android.tools.build:gradle"` version that is required EG: if i am in `9.1.?` what is the range of compatible gradle tools - versions that are suitable? This is important as everything we run currently is under `4.2.2` despite `7.2` being the latest release

**Comment by williamheelis** [comment]
PS: seems it's not on maven central, so this fixes it
https://techdocs.zebra.com/emdk-for-android/11-0/guide/setup/#gradleupdates
```allprojects {
    repositories {
        ...
        maven {
            name = "zebra-emdk"
            url = "https://zebratech.jfrog.io/artifactory/EMDK-Android/"
        }...
    }
}
```

seems emdk is not currently on maven

**Comment by jstevens-loebElectric** [comment]
Hi everyone,

I'm unfortunately still having this issue even after trying to implement all of the suggested fixes in this thread. Here's what I've done so far:

I've included the following in my build.gradle file:
`dependencies {
...
compileOnly 'com.symbol:emdk:9.1.1'
...
}`

The following is included in the structure of my manifest file:
`<manifest
...
     <uses-permission android:name="com.symbol.emdk.permission.EMDK"/>
     <application
          <uses-library android:name="com.symbol.emdk"
            android:required="false"/>
          ...
     \>
\>`

I have added the following to my remote Jar repos
![image](https://user-images.githubusercontent.com/93681484/165313938-d310de2e-aaa8-4ea4-82a3-8066d51b7e16.png)

Regardless of this all, I still receive this error upon syncing my project files with gradle:

`Failed to resolve: com.symbol:emdk:9.1.1`

I am a brand new android developer, so I apologize if my mistake here is trivial.

**Comment by jstevens-loebElectric** [comment]
> please check [my answer](https://github.com/Zebra/techdocs-archive/issues/3#issuecomment-1109947398), it works I promise you but u need api 30 android 11 or above and it is very fussy. i.e. can take a lot of persistence to see it run

Thanks for your reply! However, I need to be using Android 8.1 for the device I am specifically working with. Are there any other paths to a solution for being able to use the Zebra EMDK?

**Comment by williamheelis** [comment]
drop the  

```<queries>
        <package android:name="com.symbol.emdk.emdkservice" />
    </queries>``` 
    
    just delete it from AndroidManifest.xml
    
 I don't think it will work prior to api 30

**Comment by jstevens-loebElectric** [comment]
Like I said, I am fairly new to android development. To the best of my knowledge, I have an android manifest file that has equivalent EMDK code Your other build files are different from mine. I feel like I don't need to add the code that isn't relevant to my app, other than the stuff about EMDK. Is this hunch correct?

I have attached the files in my app build for you to look at, if you wish.

Thanks for the help

Android Manifest:
![image](https://user-images.githubusercontent.com/93681484/165389075-b5164e20-7853-4c60-a42c-848f9a3cb7b9.png)

Build.gradle:
![image](https://user-images.githubusercontent.com/93681484/165389204-633f1ee9-921b-45c5-979e-fdd38c262461.png)
(rest of build.gradle)
![image](https://user-images.githubusercontent.com/93681484/165389244-327c1412-a426-42fd-ae73-c95527b34157.png)
